package com.bbstest.mybatis.pojo;

import java.io.Serializable;

public class t_reply_indicators implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply_indicators.tri_id
     *
     * @mbggenerated
     */
    private Integer triId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply_indicators.tr_id
     *
     * @mbggenerated
     */
    private Integer trId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply_indicators.agree_count
     *
     * @mbggenerated
     */
    private Integer agreeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply_indicators.disagree_count
     *
     * @mbggenerated
     */
    private Integer disagreeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reply_indicators
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply_indicators.tri_id
     *
     * @return the value of t_reply_indicators.tri_id
     *
     * @mbggenerated
     */
    public Integer getTriId() {
        return triId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply_indicators.tri_id
     *
     * @param triId the value for t_reply_indicators.tri_id
     *
     * @mbggenerated
     */
    public void setTriId(Integer triId) {
        this.triId = triId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply_indicators.tr_id
     *
     * @return the value of t_reply_indicators.tr_id
     *
     * @mbggenerated
     */
    public Integer getTrId() {
        return trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply_indicators.tr_id
     *
     * @param trId the value for t_reply_indicators.tr_id
     *
     * @mbggenerated
     */
    public void setTrId(Integer trId) {
        this.trId = trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply_indicators.agree_count
     *
     * @return the value of t_reply_indicators.agree_count
     *
     * @mbggenerated
     */
    public Integer getAgreeCount() {
        return agreeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply_indicators.agree_count
     *
     * @param agreeCount the value for t_reply_indicators.agree_count
     *
     * @mbggenerated
     */
    public void setAgreeCount(Integer agreeCount) {
        this.agreeCount = agreeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply_indicators.disagree_count
     *
     * @return the value of t_reply_indicators.disagree_count
     *
     * @mbggenerated
     */
    public Integer getDisagreeCount() {
        return disagreeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply_indicators.disagree_count
     *
     * @param disagreeCount the value for t_reply_indicators.disagree_count
     *
     * @mbggenerated
     */
    public void setDisagreeCount(Integer disagreeCount) {
        this.disagreeCount = disagreeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_indicators
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        t_reply_indicators other = (t_reply_indicators) that;
        return (this.getTriId() == null ? other.getTriId() == null : this.getTriId().equals(other.getTriId()))
            && (this.getTrId() == null ? other.getTrId() == null : this.getTrId().equals(other.getTrId()))
            && (this.getAgreeCount() == null ? other.getAgreeCount() == null : this.getAgreeCount().equals(other.getAgreeCount()))
            && (this.getDisagreeCount() == null ? other.getDisagreeCount() == null : this.getDisagreeCount().equals(other.getDisagreeCount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_indicators
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTriId() == null) ? 0 : getTriId().hashCode());
        result = prime * result + ((getTrId() == null) ? 0 : getTrId().hashCode());
        result = prime * result + ((getAgreeCount() == null) ? 0 : getAgreeCount().hashCode());
        result = prime * result + ((getDisagreeCount() == null) ? 0 : getDisagreeCount().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_indicators
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", triId=").append(triId);
        sb.append(", trId=").append(trId);
        sb.append(", agreeCount=").append(agreeCount);
        sb.append(", disagreeCount=").append(disagreeCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}