package com.bbstest.mybatis.pojo;

import java.io.Serializable;

public class t_reply_content implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply_content.trc_id
     *
     * @mbggenerated
     */
    private Integer trcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply_content.tr_id
     *
     * @mbggenerated
     */
    private Integer trId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply_content.tr_content
     *
     * @mbggenerated
     */
    private String trContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply_content.trc_id
     *
     * @return the value of t_reply_content.trc_id
     *
     * @mbggenerated
     */
    public Integer getTrcId() {
        return trcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply_content.trc_id
     *
     * @param trcId the value for t_reply_content.trc_id
     *
     * @mbggenerated
     */
    public void setTrcId(Integer trcId) {
        this.trcId = trcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply_content.tr_id
     *
     * @return the value of t_reply_content.tr_id
     *
     * @mbggenerated
     */
    public Integer getTrId() {
        return trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply_content.tr_id
     *
     * @param trId the value for t_reply_content.tr_id
     *
     * @mbggenerated
     */
    public void setTrId(Integer trId) {
        this.trId = trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply_content.tr_content
     *
     * @return the value of t_reply_content.tr_content
     *
     * @mbggenerated
     */
    public String getTrContent() {
        return trContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply_content.tr_content
     *
     * @param trContent the value for t_reply_content.tr_content
     *
     * @mbggenerated
     */
    public void setTrContent(String trContent) {
        this.trContent = trContent == null ? null : trContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        t_reply_content other = (t_reply_content) that;
        return (this.getTrcId() == null ? other.getTrcId() == null : this.getTrcId().equals(other.getTrcId()))
            && (this.getTrId() == null ? other.getTrId() == null : this.getTrId().equals(other.getTrId()))
            && (this.getTrContent() == null ? other.getTrContent() == null : this.getTrContent().equals(other.getTrContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTrcId() == null) ? 0 : getTrcId().hashCode());
        result = prime * result + ((getTrId() == null) ? 0 : getTrId().hashCode());
        result = prime * result + ((getTrContent() == null) ? 0 : getTrContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", trcId=").append(trcId);
        sb.append(", trId=").append(trId);
        sb.append(", trContent=").append(trContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}