package com.bbstest.mybatis.pojo;

import java.io.Serializable;
import java.util.Date;

public class t_reply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.tr_id
     *
     * @mbggenerated
     */
    private Integer trId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.tp_id
     *
     * @mbggenerated
     */
    private Integer tpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.last_edit_time
     *
     * @mbggenerated
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.tr_id
     *
     * @return the value of t_reply.tr_id
     *
     * @mbggenerated
     */
    public Integer getTrId() {
        return trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.tr_id
     *
     * @param trId the value for t_reply.tr_id
     *
     * @mbggenerated
     */
    public void setTrId(Integer trId) {
        this.trId = trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.tp_id
     *
     * @return the value of t_reply.tp_id
     *
     * @mbggenerated
     */
    public Integer getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.tp_id
     *
     * @param tpId the value for t_reply.tp_id
     *
     * @mbggenerated
     */
    public void setTpId(Integer tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.u_id
     *
     * @return the value of t_reply.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.u_id
     *
     * @param uId the value for t_reply.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.last_edit_time
     *
     * @return the value of t_reply.last_edit_time
     *
     * @mbggenerated
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.last_edit_time
     *
     * @param lastEditTime the value for t_reply.last_edit_time
     *
     * @mbggenerated
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        t_reply other = (t_reply) that;
        return (this.getTrId() == null ? other.getTrId() == null : this.getTrId().equals(other.getTrId()))
            && (this.getTpId() == null ? other.getTpId() == null : this.getTpId().equals(other.getTpId()))
            && (this.getuId() == null ? other.getuId() == null : this.getuId().equals(other.getuId()))
            && (this.getLastEditTime() == null ? other.getLastEditTime() == null : this.getLastEditTime().equals(other.getLastEditTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTrId() == null) ? 0 : getTrId().hashCode());
        result = prime * result + ((getTpId() == null) ? 0 : getTpId().hashCode());
        result = prime * result + ((getuId() == null) ? 0 : getuId().hashCode());
        result = prime * result + ((getLastEditTime() == null) ? 0 : getLastEditTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", trId=").append(trId);
        sb.append(", tpId=").append(tpId);
        sb.append(", uId=").append(uId);
        sb.append(", lastEditTime=").append(lastEditTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}