package com.bbstest.mybatis.pojo;

import java.io.Serializable;

public class t_topic_content implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_content.tpc_id
     *
     * @mbggenerated
     */
    private Integer tpcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_content.tp_id
     *
     * @mbggenerated
     */
    private Integer tpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_content.tp_content
     *
     * @mbggenerated
     */
    private String tpContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_topic_content
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_content.tpc_id
     *
     * @return the value of t_topic_content.tpc_id
     *
     * @mbggenerated
     */
    public Integer getTpcId() {
        return tpcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_content.tpc_id
     *
     * @param tpcId the value for t_topic_content.tpc_id
     *
     * @mbggenerated
     */
    public void setTpcId(Integer tpcId) {
        this.tpcId = tpcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_content.tp_id
     *
     * @return the value of t_topic_content.tp_id
     *
     * @mbggenerated
     */
    public Integer getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_content.tp_id
     *
     * @param tpId the value for t_topic_content.tp_id
     *
     * @mbggenerated
     */
    public void setTpId(Integer tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_content.tp_content
     *
     * @return the value of t_topic_content.tp_content
     *
     * @mbggenerated
     */
    public String getTpContent() {
        return tpContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_content.tp_content
     *
     * @param tpContent the value for t_topic_content.tp_content
     *
     * @mbggenerated
     */
    public void setTpContent(String tpContent) {
        this.tpContent = tpContent == null ? null : tpContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_content
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        t_topic_content other = (t_topic_content) that;
        return (this.getTpcId() == null ? other.getTpcId() == null : this.getTpcId().equals(other.getTpcId()))
            && (this.getTpId() == null ? other.getTpId() == null : this.getTpId().equals(other.getTpId()))
            && (this.getTpContent() == null ? other.getTpContent() == null : this.getTpContent().equals(other.getTpContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_content
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTpcId() == null) ? 0 : getTpcId().hashCode());
        result = prime * result + ((getTpId() == null) ? 0 : getTpId().hashCode());
        result = prime * result + ((getTpContent() == null) ? 0 : getTpContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_content
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tpcId=").append(tpcId);
        sb.append(", tpId=").append(tpId);
        sb.append(", tpContent=").append(tpContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}