package com.bbstest.mybatis.pojo;

import java.io.Serializable;
import java.util.Date;

public class t_user_specific implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_sex
     *
     * @mbggenerated
     */
    private String uSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_password
     *
     * @mbggenerated
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_phone
     *
     * @mbggenerated
     */
    private String uPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_icon_url
     *
     * @mbggenerated
     */
    private String uIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_experience
     *
     * @mbggenerated
     */
    private Integer uExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_rank
     *
     * @mbggenerated
     */
    private Integer uRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_registration_date
     *
     * @mbggenerated
     */
    private Date uRegistrationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_status
     *
     * @mbggenerated
     */
    private Byte uStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_specific.u_sign
     *
     * @mbggenerated
     */
    private String uSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_specific
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_id
     *
     * @return the value of t_user_specific.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_id
     *
     * @param uId the value for t_user_specific.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_name
     *
     * @return the value of t_user_specific.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_name
     *
     * @param uName the value for t_user_specific.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_sex
     *
     * @return the value of t_user_specific.u_sex
     *
     * @mbggenerated
     */
    public String getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_sex
     *
     * @param uSex the value for t_user_specific.u_sex
     *
     * @mbggenerated
     */
    public void setuSex(String uSex) {
        this.uSex = uSex == null ? null : uSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_password
     *
     * @return the value of t_user_specific.u_password
     *
     * @mbggenerated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_password
     *
     * @param uPassword the value for t_user_specific.u_password
     *
     * @mbggenerated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_phone
     *
     * @return the value of t_user_specific.u_phone
     *
     * @mbggenerated
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_phone
     *
     * @param uPhone the value for t_user_specific.u_phone
     *
     * @mbggenerated
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone == null ? null : uPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_email
     *
     * @return the value of t_user_specific.u_email
     *
     * @mbggenerated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_email
     *
     * @param uEmail the value for t_user_specific.u_email
     *
     * @mbggenerated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_icon_url
     *
     * @return the value of t_user_specific.u_icon_url
     *
     * @mbggenerated
     */
    public String getuIconUrl() {
        return uIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_icon_url
     *
     * @param uIconUrl the value for t_user_specific.u_icon_url
     *
     * @mbggenerated
     */
    public void setuIconUrl(String uIconUrl) {
        this.uIconUrl = uIconUrl == null ? null : uIconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_experience
     *
     * @return the value of t_user_specific.u_experience
     *
     * @mbggenerated
     */
    public Integer getuExperience() {
        return uExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_experience
     *
     * @param uExperience the value for t_user_specific.u_experience
     *
     * @mbggenerated
     */
    public void setuExperience(Integer uExperience) {
        this.uExperience = uExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_rank
     *
     * @return the value of t_user_specific.u_rank
     *
     * @mbggenerated
     */
    public Integer getuRank() {
        return uRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_rank
     *
     * @param uRank the value for t_user_specific.u_rank
     *
     * @mbggenerated
     */
    public void setuRank(Integer uRank) {
        this.uRank = uRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_registration_date
     *
     * @return the value of t_user_specific.u_registration_date
     *
     * @mbggenerated
     */
    public Date getuRegistrationDate() {
        return uRegistrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_registration_date
     *
     * @param uRegistrationDate the value for t_user_specific.u_registration_date
     *
     * @mbggenerated
     */
    public void setuRegistrationDate(Date uRegistrationDate) {
        this.uRegistrationDate = uRegistrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_status
     *
     * @return the value of t_user_specific.u_status
     *
     * @mbggenerated
     */
    public Byte getuStatus() {
        return uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_status
     *
     * @param uStatus the value for t_user_specific.u_status
     *
     * @mbggenerated
     */
    public void setuStatus(Byte uStatus) {
        this.uStatus = uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_specific.u_sign
     *
     * @return the value of t_user_specific.u_sign
     *
     * @mbggenerated
     */
    public String getuSign() {
        return uSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_specific.u_sign
     *
     * @param uSign the value for t_user_specific.u_sign
     *
     * @mbggenerated
     */
    public void setuSign(String uSign) {
        this.uSign = uSign == null ? null : uSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_specific
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        t_user_specific other = (t_user_specific) that;
        return (this.getuId() == null ? other.getuId() == null : this.getuId().equals(other.getuId()))
            && (this.getuName() == null ? other.getuName() == null : this.getuName().equals(other.getuName()))
            && (this.getuSex() == null ? other.getuSex() == null : this.getuSex().equals(other.getuSex()))
            && (this.getuPassword() == null ? other.getuPassword() == null : this.getuPassword().equals(other.getuPassword()))
            && (this.getuPhone() == null ? other.getuPhone() == null : this.getuPhone().equals(other.getuPhone()))
            && (this.getuEmail() == null ? other.getuEmail() == null : this.getuEmail().equals(other.getuEmail()))
            && (this.getuIconUrl() == null ? other.getuIconUrl() == null : this.getuIconUrl().equals(other.getuIconUrl()))
            && (this.getuExperience() == null ? other.getuExperience() == null : this.getuExperience().equals(other.getuExperience()))
            && (this.getuRank() == null ? other.getuRank() == null : this.getuRank().equals(other.getuRank()))
            && (this.getuRegistrationDate() == null ? other.getuRegistrationDate() == null : this.getuRegistrationDate().equals(other.getuRegistrationDate()))
            && (this.getuStatus() == null ? other.getuStatus() == null : this.getuStatus().equals(other.getuStatus()))
            && (this.getuSign() == null ? other.getuSign() == null : this.getuSign().equals(other.getuSign()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_specific
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getuId() == null) ? 0 : getuId().hashCode());
        result = prime * result + ((getuName() == null) ? 0 : getuName().hashCode());
        result = prime * result + ((getuSex() == null) ? 0 : getuSex().hashCode());
        result = prime * result + ((getuPassword() == null) ? 0 : getuPassword().hashCode());
        result = prime * result + ((getuPhone() == null) ? 0 : getuPhone().hashCode());
        result = prime * result + ((getuEmail() == null) ? 0 : getuEmail().hashCode());
        result = prime * result + ((getuIconUrl() == null) ? 0 : getuIconUrl().hashCode());
        result = prime * result + ((getuExperience() == null) ? 0 : getuExperience().hashCode());
        result = prime * result + ((getuRank() == null) ? 0 : getuRank().hashCode());
        result = prime * result + ((getuRegistrationDate() == null) ? 0 : getuRegistrationDate().hashCode());
        result = prime * result + ((getuStatus() == null) ? 0 : getuStatus().hashCode());
        result = prime * result + ((getuSign() == null) ? 0 : getuSign().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_specific
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uId=").append(uId);
        sb.append(", uName=").append(uName);
        sb.append(", uSex=").append(uSex);
        sb.append(", uPassword=").append(uPassword);
        sb.append(", uPhone=").append(uPhone);
        sb.append(", uEmail=").append(uEmail);
        sb.append(", uIconUrl=").append(uIconUrl);
        sb.append(", uExperience=").append(uExperience);
        sb.append(", uRank=").append(uRank);
        sb.append(", uRegistrationDate=").append(uRegistrationDate);
        sb.append(", uStatus=").append(uStatus);
        sb.append(", uSign=").append(uSign);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}