package com.bbstest.mybatis.dao;

import com.bbstest.mybatis.pojo.t_category;

public interface t_categoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int insert(t_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int insertSelective(t_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    t_category selectByPrimaryKey(Short ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(t_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(t_category record);
}