package com.bbstest.mybatis.dao;

import com.bbstest.mybatis.pojo.t_reply;

public interface t_replyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    int insert(t_reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    int insertSelective(t_reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    t_reply selectByPrimaryKey(Integer trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(t_reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(t_reply record);
}