package com.bbstest.mybatis.dao;

import com.bbstest.mybatis.pojo.t_reply_content;

public interface t_reply_contentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer trcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    int insert(t_reply_content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    int insertSelective(t_reply_content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    t_reply_content selectByPrimaryKey(Integer trcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(t_reply_content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(t_reply_content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reply_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(t_reply_content record);
}