package com.bbstest.mybatis.dao;

import com.bbstest.mybatis.pojo.t_topic_indicators;

public interface t_topic_indicatorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_indicators
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tpiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_indicators
     *
     * @mbggenerated
     */
    int insert(t_topic_indicators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_indicators
     *
     * @mbggenerated
     */
    int insertSelective(t_topic_indicators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_indicators
     *
     * @mbggenerated
     */
    t_topic_indicators selectByPrimaryKey(Integer tpiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_indicators
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(t_topic_indicators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_indicators
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(t_topic_indicators record);
}