package com.bbstest.mybatis.dao;

import com.bbstest.mybatis.pojo.t_user_simple;

public interface t_user_simpleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_simple
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_simple
     *
     * @mbggenerated
     */
    int insert(t_user_simple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_simple
     *
     * @mbggenerated
     */
    int insertSelective(t_user_simple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_simple
     *
     * @mbggenerated
     */
    t_user_simple selectByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_simple
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(t_user_simple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_simple
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(t_user_simple record);
}